AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Secrets Replicator - AWS Lambda function for cross-region/cross-account
  AWS Secrets Manager replication with value transformation

Metadata:
  AWS::ServerlessRepo::Application:
    Name: 'secrets-replicator -- version %%VERSION%%'
    Description: >
      Event-driven AWS Secrets Manager replication with transformation across regions and accounts.
      Fill the gap in AWS native replication by transforming secret values during replication.
    Author: Devopspolis
    SpdxLicenseId: MIT
    LicenseUrl: ./LICENSE
    ReadmeUrl: ./README.md
    HomePageUrl: https://github.com/devopspolis/secrets-replicator
    SemanticVersion: %%SEMANTIC_VERSION%%
    SourceCodeUrl: https://github.com/devopspolis/secrets-replicator
    Labels:
      - secrets
      - secrets-manager
      - replication
      - cross-region
      - cross-account
      - disaster-recovery
      - transformation
      - lambda
      - eventbridge
      - security

Globals:
  Function:
    Timeout: 60
    Runtime: python3.12
    Architectures:
      - x86_64
    Tracing: Active

Parameters:
  Environment:
    Type: String
    Description: Deployment environment (dev, qa, or prod)
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod

  ApplicationVersion:
    Type: String
    Description: Application version (set automatically during deployment)
    Default: '%%SEMANTIC_VERSION%%'

Resources:
  # Lambda Function
  SecretReplicatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: secrets-replicator
      CodeUri: src/
      Handler: handler.lambda_handler
      Description: Replicate secrets across regions/accounts with transformations (%%VERSION%%)
      MemorySize: 256
      Environment:
        Variables:
          APP_VERSION: !Ref ApplicationVersion
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt DeadLetterQueue.Arn
      Tags:
        Application: SecretsReplicator
        Version: !Ref ApplicationVersion
      Policies:
        - Version: '2012-10-17'
          Statement:
            # Read source secrets (filtering is done in Lambda code via SECRETS_FILTER)
            - Sid: ReadSourceSecrets
              Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:DescribeSecret
              Resource: '*'

            # Read destinations config secret (for loading destination configurations)
            - Sid: ReadDestinationsConfig
              Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:secrets-replicator/config/*'

            # DENY write to config secrets (defense-in-depth security layer)
            - Sid: DenyWriteConfigSecrets
              Effect: Deny
              Action:
                - secretsmanager:CreateSecret
                - secretsmanager:PutSecretValue
                - secretsmanager:UpdateSecret
                - secretsmanager:DeleteSecret
              Resource: 'arn:aws:secretsmanager:*:*:secret:secrets-replicator/config/*'

            # Read transformation secrets (for loading transformation rules)
            - Sid: ReadTransformationSecrets
              Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:DescribeSecret
              Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:secrets-replicator/transformations/*'

            # DENY write to transformation secrets (defense-in-depth security layer)
            - Sid: DenyWriteTransformationSecrets
              Effect: Deny
              Action:
                - secretsmanager:CreateSecret
                - secretsmanager:PutSecretValue
                - secretsmanager:UpdateSecret
                - secretsmanager:DeleteSecret
              Resource: 'arn:aws:secretsmanager:*:*:secret:secrets-replicator/transformations/*'

            # Read filter secrets (for loading filter configuration)
            - Sid: ReadFilterSecrets
              Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:secrets-replicator/filters/*'

            # DENY write to filter secrets (defense-in-depth security layer)
            - Sid: DenyWriteFilterSecrets
              Effect: Deny
              Action:
                - secretsmanager:CreateSecret
                - secretsmanager:PutSecretValue
                - secretsmanager:UpdateSecret
                - secretsmanager:DeleteSecret
              Resource: 'arn:aws:secretsmanager:*:*:secret:secrets-replicator/filters/*'

            # Read name mapping secrets (for loading name mapping configuration)
            - Sid: ReadNameMappingSecrets
              Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:secrets-replicator/names/*'

            # DENY write to name mapping secrets (defense-in-depth security layer)
            - Sid: DenyWriteNameMappingSecrets
              Effect: Deny
              Action:
                - secretsmanager:CreateSecret
                - secretsmanager:PutSecretValue
                - secretsmanager:UpdateSecret
                - secretsmanager:DeleteSecret
              Resource: 'arn:aws:secretsmanager:*:*:secret:secrets-replicator/names/*'

            # Write destination secrets (same account)
            - Sid: WriteDestinationSecrets
              Effect: Allow
              Action:
                - secretsmanager:CreateSecret
                - secretsmanager:PutSecretValue
                - secretsmanager:DescribeSecret
                - secretsmanager:TagResource
              Resource: '*'

            # KMS permissions for decrypting source secrets
            - Sid: KMSDecryptSource
              Effect: Allow
              Action:
                - kms:Decrypt
                - kms:DescribeKey
              Resource: '*'
              Condition:
                StringEquals:
                  'kms:ViaService': !Sub 'secretsmanager.${AWS::Region}.amazonaws.com'

            # KMS permissions for encrypting destination secrets (any region)
            - Sid: KMSEncryptDestination
              Effect: Allow
              Action:
                - kms:Encrypt
                - kms:GenerateDataKey
                - kms:DescribeKey
              Resource: '*'
              Condition:
                StringLike:
                  'kms:ViaService': 'secretsmanager.*.amazonaws.com'

            # Assume role for cross-account (if configured)
            - Sid: AssumeDestinationRole
              Effect: Allow
              Action:
                - sts:AssumeRole
              Resource: '*'

            # Publish CloudWatch metrics
            - Sid: PublishMetrics
              Effect: Allow
              Action:
                - cloudwatch:PutMetricData
              Resource: '*'
              Condition:
                StringEquals:
                  'cloudwatch:namespace': 'SecretsReplicator'

            # Send to Dead Letter Queue
            - Sid: SendToDLQ
              Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: !GetAtt DeadLetterQueue.Arn
      Events:
        SecretUpdateEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - aws.secretsmanager
              detail-type:
                - AWS API Call via CloudTrail
                - AWS Service Event
              detail:
                eventName:
                  - CreateSecret
                  - PutSecretValue
                  - UpdateSecret
                  - ReplicateSecretToRegions
                  - ReplicateSecretVersion

  # Dead Letter Queue for failed events
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${AWS::StackName}-dlq
      KmsMasterKeyId: alias/aws/sqs
      MessageRetentionPeriod: 1209600  # 14 days
      Tags:
        - Key: Application
          Value: SecretsReplicator
        - Key: Version
          Value: !Ref ApplicationVersion

  # CloudWatch Alarm for DLQ
  DeadLetterQueueAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-dlq-messages
      AlarmDescription: Alert when messages appear in DLQ
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt DeadLetterQueue.QueueName
      AlarmActions:
        - !Ref AlertTopic

  # CloudWatch Alarm for Lambda errors
  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-lambda-errors
      AlarmDescription: Alert when Lambda function errors occur
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref SecretReplicatorFunction
      AlarmActions:
        - !Ref AlertTopic

  # CloudWatch Alarm for high replication failure rate
  ReplicationFailureAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-replication-failures
      AlarmDescription: Alert when replication failure rate is high
      MetricName: ReplicationFailure
      Namespace: SecretsReplicator
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertTopic

  # CloudWatch Alarm for high throttling rate
  ThrottlingAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-throttling-events
      AlarmDescription: Alert when AWS API throttling occurs frequently
      MetricName: ThrottlingEvent
      Namespace: SecretsReplicator
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 10
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertTopic

  # CloudWatch Alarm for high replication duration
  HighDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-high-duration
      AlarmDescription: Alert when replication duration is consistently high
      MetricName: ReplicationDuration
      Namespace: SecretsReplicator
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 5000
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertTopic

  # SNS Topic for alerts
  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${AWS::StackName}-alerts
      DisplayName: Secrets Replicator Alerts
      KmsMasterKeyId: alias/aws/sns
      Tags:
        - Key: Application
          Value: SecretsReplicator
        - Key: Version
          Value: !Ref ApplicationVersion

Outputs:
  ApplicationVersion:
    Description: Deployed application version
    Value: !Ref ApplicationVersion
    Export:
      Name: !Sub ${AWS::StackName}-Version

  SecretReplicatorFunctionArn:
    Description: ARN of the Secret Replicator Lambda function
    Value: !GetAtt SecretReplicatorFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-FunctionArn

  SecretReplicatorFunctionName:
    Description: Name of the Secret Replicator Lambda function
    Value: !Ref SecretReplicatorFunction
    Export:
      Name: !Sub ${AWS::StackName}-FunctionName

  DeadLetterQueueUrl:
    Description: URL of the Dead Letter Queue
    Value: !Ref DeadLetterQueue
    Export:
      Name: !Sub ${AWS::StackName}-DLQUrl

  DeadLetterQueueArn:
    Description: ARN of the Dead Letter Queue
    Value: !GetAtt DeadLetterQueue.Arn
    Export:
      Name: !Sub ${AWS::StackName}-DLQArn

  AlertTopicArn:
    Description: ARN of the SNS Alert Topic
    Value: !Ref AlertTopic
    Export:
      Name: !Sub ${AWS::StackName}-AlertTopicArn
